# Generated by Django 3.0.5 on 2020-04-21 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
