# Generated by Django 3.0.5 on 2020-04-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_tool_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='state_of_use',
            field=models.CharField(choices=[('New', 'Comme neuf'), ('Medium', 'Moyen'), ('Old', 'Usé')], default='Medium', max_length=100),
        ),
    ]
