# Generated by Django 3.0.5 on 2020-05-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_tool_state_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tool_pics'),
        ),
    ]
