# Generated by Django 3.0.5 on 2020-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_end',
            field=models.DateField(),
        ),
    ]
