# Generated by Django 3.0.5 on 2020-05-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200421_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date_end',
        ),
    ]
