# Generated by Django 3.0.5 on 2020-05-03 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20200502_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
