# Generated by Django 3.0.5 on 2020-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('New', 'demandé'), ('Accepted', 'accepté'), ('Rejected', 'refusé'), ('InProgress', 'prêt en cours'), ('ToolReturned', 'outil rendu'), ('Completed', 'terminé')], default='New', max_length=100),
        ),
    ]
