# Generated by Django 3.0.5 on 2020-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        ('loans', '0007_auto_20200505_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='messages',
            field=models.ManyToManyField(to='discussion.Message'),
        ),
    ]
