# Generated by Django 3.0.5 on 2020-05-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loan_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower_grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='tool_owner_grade',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
