# Generated by Django 3.0.5 on 2020-05-23 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0010_auto_20200523_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoanScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('score', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
